# Generated by Django 6.0.4 on 2026-04-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='payment_method',
        ),
    ]
