# Generated by Django 6.0.4 on 2026-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='rate_type',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('short', 'Short Stay'), ('overstay', 'Overstay')], max_length=10, null=True),
        ),
    ]
