# Generated by Django 6.0.4 on 2026-04-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
