# Generated by Django 6.0.4 on 2026-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_registration_nin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
