# Generated by Django 6.0.4 on 2026-04-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_registration_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='pyment_method',
            new_name='payment_method',
        ),
    ]
