# Generated by Django 6.0.4 on 2026-04-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_method_payment_payment_method'),
        ('vehicle', '0004_rename_pyment_method_registration_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Personal car', 'Personal car'), ('Taxi', 'Taxi'), ('Coaster', 'Coaster'), ('Boda-boda', 'Boda-boda')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment'),
        ),
    ]
