# Generated by Django 6.0.4 on 2026-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_category_vehicle_type_alter_registration_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
