# Generated by Django 6.0.4 on 2026-04-29 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('battery_type', models.CharField(choices=[('hire', 'Battery Hire'), ('sale', 'Battery Sale')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pressure', 'Tyre Pressure'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10)),
                ('vehicle_size', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
