# Generated by Django 6.0.4 on 2026-04-25 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pressure', 'Tyre Pressure'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement')], max_length=20)),
                ('vehicle_size', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('battery_type', models.CharField(choices=[('Battery hire', 'Battery Hire'), ('Battery sale', 'Battery Sale')], default='Battery hire', max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
