# Generated by Django 6.0.4 on 2026-04-27 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_method_payment_payment_method'),
        ('service', '0003_tyre_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='Payment_method',
        ),
        migrations.RemoveField(
            model_name='service',
            name='model',
        ),
        migrations.RemoveField(
            model_name='service',
            name='vehicle_size',
        ),
        migrations.AddField(
            model_name='tyre',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tyre',
            name='vehicle_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='battery_type',
            field=models.CharField(choices=[('hire', 'Battery Hire'), ('sale', 'Battery Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='battery',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='battery',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('pressure', 'Tyre Pressure'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='battery',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment'),
        ),
    ]
