# Generated by Django 6.0.4 on 2026-04-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_battery_payment_method_remove_service_model_and_more'),
        ('vehicle', '0006_alter_registration_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.registration'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.registration'),
        ),
    ]
