# Generated by Django 6.0.4 on 2026-04-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_battery_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Card')], max_length=20, null=True),
        ),
    ]
